### ISSUE TITLE
Warning! Error encountered during contract execution [execution reverted] 

### ISSUE THREAD

**Issue by bpevreall** [yuichiroaoki/poly-flashloan-bot#18] opened 2022-01-08 00:54 UTC
seems to happen with every transaction 

https://polygonscan.com/tx/0x3cd38115cdea6b0fbcfcd441de5891236eb802fe0863a63cba9c336ce6ac6c83

**Comment by yuichiroaoki** [comment] 2022-01-08 10:43
Duplicate of #10

**Closed by yuichiroaoki** 2022-01-08 10:43 UTC
Labels: duplicate
