### ISSUE TITLE
Fail with error 'AS'

### ISSUE THREAD

**Issue by ezera23** [yuichiroaoki/poly-flashloan-bot#25] opened 2022-01-13 11:41 UTC
Hi guys,

New error here, I will continue my tests.

Fail with error 'AS'

Contract address: https://polygonscan.com/tx/0xf976a46752e1d447b9681b88ff52e6eda63db3b590f27b932492a40aab2854f7

![Screenshot_20220113-184917_JuiceSSH](https://user-images.githubusercontent.com/6976777/149325223-01522bf7-0c15-4a27-a0cb-4a57cc600b85.jpg)

**Comment by iouae** [comment] 2022-01-13 11:48
Duplicate of [#18](https://github.com/yuichiroaoki/poly-flash/issues/18)

**Closed** 2022-01-14 11:27 UTC
