### ISSUE TITLE
Error: replacement fee too low

### ISSUE THREAD

**Issue by trancee** [yuichiroaoki/poly-flashloan-bot#7] opened 2021-12-15 16:31 UTC
I have found an arbitrage opportunity and it handed it over to the flashloan smart contract, but then it failed with this error message:
```
Error: replacement fee too low
```
Additionally, I have attached the log output thrown by the script, maybe it helps to investigate this issue.
[log.txt](https://github.com/yuichiroaoki/poly-flashloan-bot/files/7721103/log.txt)

And there were 2 transactions on Polygon:
https://polygonscan.com/tx/0xd8595edf297a3d5760b1fde6bdaafa0d1c08bf3f9225bd2f1bd1ab405759e6d8
https://polygonscan.com/tx/0x0b2893428bc9919ab742578b03121e71b88f6fa6404ef4c71519e943eed17113

Do you have an idea why this error is happening and how to prevent it?

**Comment by yuichiroaoki** [comment] 2021-12-17 02:10
Sorry, I'm not sure about the ```replacement fee too low``` error. 
Do you know how to reproduce that error?

I just opened issues for the last two errors.
https://github.com/yuichiroaoki/poly-flashloan-bot/issues/9
https://github.com/yuichiroaoki/poly-flashloan-bot/issues/8

**Comment by iouae** [comment] 2021-12-17 06:39
> Error: replacement fee too low
Good evening, are you using Metamask?

Found this one, seems to be Metamask problem.
https://community.metamask.io/t/all-matic-transactions-failing/4481

**Comment by iouae** [comment] 2021-12-17 06:41
> Error: replacement fee too low

Hello, are you using Metamask?

Found this one, seems to be Metamask problem.
https://community.metamask.io/t/all-matic-transactions-failing/4481/2

**Comment by trancee** [comment] 2021-12-17 07:31
> Sorry, I'm not sure about the replacement fee too low error.
Do you know how to reproduce that error

I think I figured out why this error happened. It was when there were more than one arbitrage opportunity at the same time and the bot started multiple transactions. So the network thought the bot wanted to replace the previous transaction. I have solved this issue by only allowing one transaction at the time.

**Comment by yuichiroaoki** [comment] 2021-12-18 00:17
@trancee Thank you for resolving that issue and adding great console UI!!

**Closed** 2022-01-24 23:44 UTC
